name: erudio.cleaning
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - numpy
    - matplotlib
    - seaborn
    - pandas
    - scikit-learn
    - pip
    - requests
    - tornado
    - numexpr
    - pyarrow
    - pytables
    - pyreadstat
    - simplejson
    - seqkit
    - llvmlite
    - pip:
        - beautifulsoup4
        - csvkit
        - fuzzy
        - gensim
        - h5py
        - jupyter
        - jupyterlab
        - lxml
        - Metaphone
        - nltk
        - xlrd
        - openpyxl
        - psycopg2
        - pymongo
        - rise
        - sqlalchemy
        - sqlalchemy-utils
        - umap-learn
        - imbalanced-learn
        - toml
        - pytest
